services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql_test/data
    command: ['postgres', '-c', 'ssl=off']
    restart: 'always'

volumes:
  postgres_data:

networks:
  backend:
